[package]
name = "html_to_pdf_lib"
version = "0.1.2"
edition = "2021"

# Required fields
description = "A library for converting HTML to PDF."
license = "MIT"

[dependencies]
printpdf = "0.7.0"  # Use a version known to work
scraper = "0.12.0"
anyhow = "1.0"
