name: Publish Release

on:
  push:
    branches:
      - master

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Choose a Node.js version compatible with rustup

      - name: Install Rustup
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -y

      - name: Install stable Rust (optional)
        run: rustup install stable

      - name: Configure Cargo credentials
        run: |
          mkdir -p ~/.cargo
          echo '[registries.crates.io]' > ~/.cargo/config
          echo 'token = "${{ secrets.CARGO_REGISTRY_TOKEN }}"' >> ~/.cargo/config

      - name: Build release
        run: cargo build --release

      - name: Test release (optional)
        run: cargo test --release  # Uncomment to run tests

      - name: Publish to crates.io
        run: cargo publish --release
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
