name: Publish Release

on:
  push:
    branches:
      - master  # Trigger workflow on pushes to the master branch

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Add Rust to PATH
        run: echo "::add-path::${HOME}/.cargo/bin"

      - name: Build release
        run: cargo build --release

      - name: Test release (optional)
        run: cargo test --release  # Uncomment to run tests

  push_release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Add Rust to PATH
        run: echo "::add-path::${HOME}/.cargo/bin"

      - name: Configure Cargo credentials
        run: |
          mkdir -p ~/.cargo
          echo '[registries.crates-io]' > ~/.cargo/config
          echo 'token = "${{ secrets.CARGO_REGISTRY_TOKEN }}"' >> ~/.cargo/config

      - name: Publish to crates.io
        run: cargo publish --release
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
