name: Publish Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: '1.72.0'  # Specify the Rust version you need

      - name: Build project
        run: cargo build --release

      - name: Create a Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: elgohr/github-release-action@v5
        with:
          files: |
            target/release/your_binary_name
            # Add other artifacts if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for creating releases
